language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - travis_wait 15 mvn install
# command to run tests
script:
  - python -m unittest discover test